name: vcclient-dev-bsc  # Change this to whatever you want to name your environment
channels:
  - conda-forge
dependencies:
  - python=3.10  # or match your desired Python version
  - pip
  - onnxruntime-gpu=1.13.1
  - fairseq
  - pip:
      - uvicorn==0.21.1
      - pyOpenSSL==23.1.1
      - numpy==1.23.5
      - torch==2.0.1
      - torchaudio==2.0.2
      - resampy==0.4.2
      - python-socketio==5.8.0
      - fastapi==0.95.1
      - python-multipart==0.0.6
      - scipy==1.10.1
      - matplotlib==3.7.1
      - websockets==11.0.2
      - faiss-cpu==1.7.3
      - torchcrepe==0.0.18
      - librosa==0.9.1
      - gin==0.1.6
      - gin_config==0.5.0
      - einops==0.6.0
      - local_attention==1.8.5
      - sounddevice==0.4.6
      - dataclasses_json==0.5.7
      - onnxsim==0.4.28
      - torchfcpe==0.0.3
